Repository actionhero/actionhero, pull requests merged in 2020-11, with the labels that each got.

#1639 client state to 'connected' on reconnect event
  client/ActionheroWebsocketClient.js
Labels: bug

#1641 Suppress "Job already enqueued at this time with same arguments" errors with recurring tasks
  __tests__/core/tasks/fullWorkerFlow.ts
  package-lock.json
  package.json
  src/modules/task.ts
Labels: enhancement

#1642 Add a Dedication to the Readme
  README.md
Labels: documentation

#1647 Enable status action and show more useful errors when redis is disabled
  public/chat.html
  src/actions/status.ts
  src/modules/chatRoom.ts
Labels: enhancement

#1643 Replace up to 5 params in routes for swagger
  src/actions/swagger.ts
Labels: bug

#1562 Browser tests with Puppeteer rather than Selenium
  .github/workflows/test.yml
  __tests__/integration/browser.ts
  package-lock.json
  package.json
Labels: help wanted, internal

#1653 Actionhero can be run with ioredis-mock (Redis is always enabled)
  __tests__/integration/ioredis-mock.ts
  package-lock.json
  package.json
  src/actions/status.ts
  src/config/redis.ts
  src/initializers/chatRoom.ts
  src/initializers/redis.ts
  src/initializers/resque.ts
  src/initializers/tasks.ts
  src/modules/cache.ts
  src/modules/chatRoom.ts
  src/modules/specHelper.ts
  templates/package.json.template
Labels: BREAKING-CHANGE, enhancement

#1660 Update dependencies
  __tests__/core/middleware.ts
  __tests__/servers/websocket.ts
  __tests__/testPlugin/src/actions/pluginAction.ts
  package-lock.json
  package.json
  src/actions/status.ts
  src/classes/action.ts
  src/classes/server.ts
  src/classes/task.ts
  src/initializers/staticFile.ts
  src/servers/web.ts
Labels: dependencies, enhancement

#1661 Default action logging output to match action result returned to web client.
  __tests__/servers/web/routes/routes.ts
  __tests__/servers/web/web.ts
  src/config/servers/web.ts
  src/modules/utils/filterResponseForLogging.ts
  src/servers/web.ts
Labels: BREAKING-CHANGE
