Repository actionhero/actionhero, pull requests merged in 2020-06, with the labels that each got.

#1483 Add a Code of Conduct for the Actionhero Community
  .github/CONTRIBUTING.md
  CODE_OF_CONDUCT.md
  README.md
Labels: enhancement, internal

#1494 Add action response to logger and user can disable and filter private…
  __tests__/utils/utils.ts
  src/classes/actionProcessor.ts
  src/config/api.ts
  src/modules/utils.ts
  src/modules/utils/filterResponseForLogging.ts
Labels: enhancement

#1495 Trim protocol from allowedRequestHosts when building swagger routes
  src/actions/swagger.ts
Labels: bug

#1505 Action and Task errors log on only one line
  src/classes/actionProcessor.ts
  src/initializers/exceptions.ts
Labels: BREAKING-CHANGE, enhancement

#1506 When using simpleRouting, the shown swagger route is be GET
  src/actions/swagger.ts
Labels: enhancement
