Repository actionhero/actionhero, pull requests merged in 2020-09, with the labels that each got.

#1578 Do not stop the shutdown timer on the second SIGINT/SIGTERM
  src/classes/process.ts
Labels: bug

#1583 Update Dockerfile base image to node:alpine
  Dockerfile
  docker-compose.yml
Labels: internal

#1590 Connect to Resque Queue at in initialize lifecycle step
  src/bin/methods/task/enqueue.ts
  src/initializers/resque.ts
  src/initializers/tasks.ts
Labels: enhancement
