Repository actionhero/actionhero, pull requests merged in 2022-01, with the labels that each got.

#2074 VSCode Devcontainer
  .devcontainer/devcontainer.json
  .devcontainer/setup.sh
Labels: enhancement, internal

#2075 Skip typechck in test when ignoring await
  __tests__/servers/web/rawBody.ts
Labels: bug, internal

#2083 export `rebuildConfig` method
  src/index.ts
Labels: enhancement

#2106 Bump node-resque and ioredis-mock
  __tests__/integration/ioredis-mock.ts
  package-lock.json
  package.json
  src/config/logger.ts
  src/config/redis.ts
  src/initializers/redis.ts
Labels: dependencies

#2099 use commander to handle cli `formatter`/`validator`
  __tests__/cli/cli.ts
  __tests__/testCliCommands/hello.ts
  package.json
  src/bin/actionhero.ts
  src/classes/inputs.ts
Labels: enhancement

#2107 cli command optional inputs can require a value
  __tests__/cli/cli.ts
  __tests__/testCliCommands/hello.ts
  src/bin/actionhero.ts
  src/classes/cli.ts
Labels: enhancement

#2108 fix `ParamsFrom` type inference
  __tests__/testCliCommands/hello.ts
  src/classes/inputs.ts
Labels: bug
